name: Publish and Deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: contains(github.ref, 'master') # Publish it only if the push comes from the master branch
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Version update detected
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - uses: bahmutov/npm-install@v1
        with: 
          install-command: yarn --ignore-optional
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: addons/AutoAnnotate
    
      - run: npm run build

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dna-script-inc'

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # - uses: JS-DevTools/npm-publish@v1
      #   # if: steps.check.outputs.changed == 'true'
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     registry: https://npm.pkg.github.com
      #     access: restricted
